'use client';

import { Check, Flag, Map as MapIcon, Plus } from 'lucide-react';
import { useAppStore } from '@/lib/store';
import { Card } from '@/components/ui/Card';
import { PixelButton } from '@/components/ui/PixelButton';

export default function MapPage() {
  const { state, dispatch } = useAppStore();
  const toggleMilestone = (projectId: string, milestoneId: string) => {
    const project = state.projects.find((item) => item.id === projectId);
    if (!project) return;
    dispatch({ type: 'UPDATE_PROJECT', payload: { id: projectId, updates: { milestones: project.milestones.map((milestone) => milestone.id === milestoneId ? { ...milestone, isCompleted: !milestone.isCompleted, completedAt: !milestone.isCompleted ? new Date().toISOString() : null } : milestone) } } });
  };
  return <div className="mx-auto max-w-6xl px-4 py-6 sm:px-6 sm:py-8"><header className="mb-7 flex flex-col gap-4 border-b-2 border-base-border pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 font-pixel text-[9px] text-accent-warning">CAMPAIGN MAP</p><h1 className="font-pixel text-xl text-text-primary">YOUR LONG GAME</h1><p className="mt-2 text-sm text-text-secondary">Milestones turn big goals into a path you can actually walk.</p></div><PixelButton variant="ghost" size="sm" disabled><Plus className="mr-2 h-3 w-3"/> NEW CAMPAIGN</PixelButton></header><div className="grid gap-6 lg:grid-cols-2">{state.projects.map((project) => { const cleared = project.milestones.filter((item) => item.isCompleted).length; const progress = Math.round((cleared / project.milestones.length) * 100); return <Card key={project.id} variant="highlight" className="overflow-hidden p-0"><div className="border-b-2 border-base-border p-5" style={{ borderLeftColor: project.color, borderLeftWidth: 6 }}><div className="flex items-start gap-4"><span className="text-3xl">{project.icon}</span><div><h2 className="font-semibold text-text-primary">{project.title}</h2><p className="mt-1 text-sm text-text-secondary">{project.description}</p></div></div><div className="mt-4 flex justify-between text-xs text-text-secondary"><span>{cleared} / {project.milestones.length} milestones</span><span className="font-pixel text-[9px]" style={{ color: project.color }}>{progress}%</span></div></div><ol className="relative space-y-0 p-5">{project.milestones.map((milestone, index) => <li key={milestone.id} className="relative flex gap-4 pb-5 last:pb-0"><div className="flex flex-col items-center"><button aria-label={`Toggle ${milestone.title}`} onClick={() => toggleMilestone(project.id, milestone.id)} className={`z-10 flex h-7 w-7 items-center justify-center rounded-full border-2 ${milestone.isCompleted ? 'border-accent-primary bg-accent-primary text-bg-base' : 'border-base-border bg-base text-text-secondary'}`}>{milestone.isCompleted ? <Check className="h-4 w-4"/> : <Flag className="h-3 w-3"/>}</button>{index < project.milestones.length - 1 && <span className="absolute top-7 h-[calc(100%-28px)] w-px bg-base-border"/>}</div><button onClick={() => toggleMilestone(project.id, milestone.id)} className="pt-0.5 text-left"><span className={`block text-sm font-semibold ${milestone.isCompleted ? 'text-text-secondary line-through' : 'text-text-primary'}`}>{milestone.title}</span><span className="mt-1 block text-xs text-text-secondary">{milestone.description}</span></button></li>)}</ol></Card>})}</div>{state.projects.length === 0 && <Card className="py-16 text-center"><MapIcon className="mx-auto h-10 w-10 text-accent-secondary"/><p className="mt-4 font-pixel text-sm">YOUR MAP IS WAITING</p><p className="mt-2 text-sm text-text-secondary">Create a campaign when you are ready to turn a big goal into milestones.</p></Card>}</div>;
}
